[package]
org = "ballerinax"
name = "FHIRRepoSync"
version = "1.0.0"
export = ["FHIRRepoSync"]
distribution = "2201.4.1"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Repository","Synchronize"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
