// // Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.

// This software is the property of WSO2 LLC. and its suppliers, if any.
// Dissemination of any information or reproduction of any material contained
// herein is strictly forbidden, unless permitted by WSO2 in accordance with
// the WSO2 Software License available at: https://wso2.com/licenses/eula/3.2
// For specific language governing the permissions and limitations under
// this license, please see the license as well as any agreement you’ve
// entered into with WSO2 governing the purchase of this software and any
// associated services.
//
//
// AUTO-GENERATED FILE.
//
// This file is auto-generated by WSO2 Healthcare Team for implementing resource functions.
// Developers are allowed modify this file as per the requirement.

import ballerinax/health.fhir.r4;
import ballerinax/health.fhirr4;

# A service representing a network-accessible API
# bound to port `9090`.
service / on new fhirr4:Listener(9090, apiConfig) {


    // Read the current state of the resource
    resource function get fhir/r4/Patient/[string id](r4:FHIRContext fhirContext) returns r4:Patient|r4:FHIRError? {

            r4:Patient fhirPatient = {
            birthDate: "1989-04-29",
            id: "321444",
            active: false,
            gender: "male"
        };
        return fhirPatient;
    }
}
