[package]
org = "ballerinax"
name = "test_epicconnect"
version = "1.0.0"
export = ["test_epicconnect"]
distribution = "2201.4.1"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Epic"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
