[package]
org = "ballerinax"
name = "test_patientAPI_template102"
version = "1.0.2"
export = ["test_patientAPI_template102"]
distribution = "2201.4.1"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Patient","r4","international"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
