[package]
org = "ballerinax"
name = "test_metadata"
version = "1.0.0"
export = ["test_metadata.config","test_metadata.constants","test_metadata.handlers","test_metadata.models","test_metadata.samples"]
distribution = "2201.4.1"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Metadata"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
